// appointment-app/src/features/services/list/ServiceItem.tsx
import React from "react";
import Service from "../../../app/models/Service";
import {Button, Card, Header, Image, Segment} from "semantic-ui-react";
import {NavLink} from "react-router-dom";

interface Props {
    service: Service
}

export default function ServiceItem({service}: Props) {
    return (
        <Card>
            <Segment textAlign='center'
                     attached='top'
                     inverted
                     color='teal'
                     style={{border: 'none'}}
            >
                <Header>{service.title}</Header>
            </Segment>
            <Image src={service.image || "/assets/service.png"}/>
            <Card.Content>
                <Card.Description>
                    {service.description}
                </Card.Description>
            </Card.Content>
            <Card.Content extra>
                <Button as={NavLink} to={`/services/${service.id}`} positive>Подробнее</Button>
            </Card.Content>
        </Card>
    )
}

// appointment-app/src/components/services/ServiceItem.vue
<template>
  <div>
    <base-card>
      <header>
        <h2>{{ service.title }}</h2>
      </header>
      <img alt="" :src="image" />
      <h4>{{ service.description }}</h4>
      <router-link :to="serviceLink">Подробнее</router-link>
    </base-card>
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from "vue";
import Service from "@/models/Service";

export default defineComponent({
  name: "ServiceItem",
  props: {
    service: {
      type: Object as PropType<Service>,
      required: true,
    },
  },
  computed: {
    image() {
      return this.service.image
        ? this.service.image
        : require("../../assets/service.png");
    },
    serviceLink() {
      return this.$route.path + "/" + this.service.id;
    },
  },
});
</script>

<style scoped>
img {
  width: 150px;
  height: 150px;
}
</style>
